terraform {
  required_version = ">= 1.0.0"
  required_providers {
    github = {
      source  = "hashicorp/github"
      version = "~> 6.0"
    }
  }
}

provider "github" {
  token = var.github_token
  owner = var.github_owner
}

locals {
  repo_name = var.repo_name != "" ? var.repo_name : "auto-repo-${formatdate("20060102150405", timestamp())}"
}

resource "github_repository" "new" {
  name        = local.repo_name
  description = "Private repo created by Terraform from GitHub Actions"
  visibility  = "private"
  auto_init   = true
  has_issues  = true
  has_projects = false
  has_wiki    = false
  
  vulnerability_alerts = true
  archive_on_destroy   = true

  lifecycle {
    prevent_destroy = false
  }
}

resource "github_repository_file" "readme" {
  repository     = github_repository.new.name
  file           = "README.md"
  content        = "terraform öğreniyorum\n"
  commit_message = "Add autogenerated README"
  overwrite_on_create = true
  branch         = github_repository.new.default_branch

  depends_on = [github_repository.new]
}
