// Terraform blok: hangi provider'ların gerektiğini ve Terraform sürümü gereksinimini belirtir.
// Bu blok Terraform'un çalışma zamanı ve provider sürüm uyumluluğunu sağlar.
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    github = {
      source  = "hashicorp/github"
      version = "~> 4.0"
    }
  }
}

// Provider konfigürasyonu: GitHub ile konuşmak için gerekli token ve owner bilgisi burada verilir.
// `token` sensitive bilgidir; workflow içinde secret olarak sağlanır.
provider "github" {
  token = var.github_token
  owner = var.github_owner
}

// Locals: repo ismi için kullanılacak mantık burada. Eğer kullanıcı `repo_name` vermediyse
// timestamp içeren benzersiz bir isim üretilir. Bu sayede her run farklı bir repo yaratır.
locals {
  # Kullanıcı `repo_name` verirse onu kullan; yoksa timestamp ile benzersiz isim oluştur.
  # Not: Terraform'un formatdate() fonksiyonu Go zaman formatını kullanır (örnek: 2006=YYYY, 01=MM, 02=DD, 15=HH, 04=MM, 05=SS).
  # Bu yüzden 'YYYYMMDDHHMMSS' gibi ifadeler çalışmaz; aşağıdaki layout doğru bir zaman damgası üretir.
  repo_name = var.repo_name != "" ? var.repo_name : "auto-repo-${formatdate("20060102150405", timestamp())}"
}

// Kaynak: GitHub üzerinde yeni bir repository oluşturur.
// Burada visibility private olarak ayarlandı; ayrıca issue/wiki gibi özellikler konfigüre edilebilir.
resource "github_repository" "new" {
  name        = local.repo_name
  description = "Private repo created by Terraform from GitHub Actions"
  visibility  = "private"
  # auto_init ile repository'ye ilk commit (default README) oluşturulur.
  # Bu sayede daha sonra dosya eklemeye çalıştığımızda default branch (ör. main)
  # mevcut olur ve 404/Not Found hatası almayız.
  auto_init = true
  has_issues   = true
  has_projects = false
  has_wiki     = false
}

// Yeni oluşturulan repoya otomatik olarak README.md dosyası eklemek için
// `github_repository_file` kaynağını kullanıyoruz. Bu kaynak, repository
// oluşturulduktan sonra çalışmalı — bu yüzden explicit olarak depends_on ekledik.
resource "github_repository_file" "readme" {
  repository     = github_repository.new.name
  file           = "README.md"
  content        = "terraform öğreniyorum\n"
  commit_message = "Add autogenerated README"
  # branch yerine repository'nin default_branch attribute'unu kullanıyoruz.
  # Böylece hangi isimde branch oluşturulursa (main/master) uyumlu olur.
  branch         = github_repository.new.default_branch

  # Ensure the repo exists before trying to create the file
  depends_on = [github_repository.new]
}
