resource "local_file" "pet" {
    filename = var.filename[0]
    content = var.file-content["statement1"]
}

resource "local_file" "pet_readonly" {
  filename = var.filename[1]
  content = var.file-content["statement2"]
  file_permission = var.file-permission["read-only"]
}

resource "local_sensitive_file" "pet_local_sensitive_file" {
  filename = var.filename[2]
  content  = var.file-content["statement3"]
}

resource "local_file" "my_pet_file" {
  filename = var.filename[3]
  content = "My favorite pet is ${random_pet.my_pet.id}"

  depends_on = [ 
    random_pet.my_pet
   ]
}

resource "random_pet" "my_pet" {
  prefix = var.prefix[0]
  separator = var.separator
  length    = var.length
  
}

output "my_pet_name" {
  value = random_pet.my_pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}

resource "null_resource" "trigger" {
  triggers = {
    isim = random_pet.my_pet.id
  }

  provisioner "local-exec" {
    command = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File ./greeting.ps1 ${random_pet.my_pet.id}"
  }
}